apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
  namespace: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
        - name: doctor-service
          image: medicareacr.azurecr.io/healthcare/doctor-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: '3000'
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: MONGO_URI_DOCTOR
          envFrom:
            - configMapRef:
                name: platform-config
            - secretRef:
                name: platform-secrets
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 384Mi
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-service
  namespace: healthcare
spec:
  selector:
    app: doctor-service
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
