apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: medicareacr.azurecr.io/healthcare/notification-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3008
          env:
            - name: PORT
              value: '3008'
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: MONGO_URI_NOTIFICATION
          envFrom:
            - configMapRef:
                name: platform-config
            - secretRef:
                name: platform-secrets
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 384Mi
          livenessProbe:
            tcpSocket:
              port: 3008
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 3008
            initialDelaySeconds: 10
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: healthcare
spec:
  selector:
    app: notification-service
  ports:
    - port: 3008
      targetPort: 3008
  type: ClusterIP
